// Northern Colorado Business Demo Data
// Each business gets a fully customized app demo

const BUSINESSES = [
  // ─────────────────────────────────────────────
  // 1. MED SPA — Renew Beauty Med Spa (Fort Collins)
  // ─────────────────────────────────────────────
  {
    id: 'renew-beauty',
    name: 'Renew Beauty Med Spa',
    tagline: 'Reveal Your Best Self',
    type: 'Med Spa',
    city: 'Fort Collins',
    state: 'CO',
    address: '2608 S Timberline Rd, Fort Collins, CO 80525',
    phone: '(970) 631-8337',
    website: 'renewbeautymedspa.com',
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '17:00' },
      saturday: { open: '10:00', close: '14:00' },
      sunday: null,
    },
    colors: {
      primary: '#c4917b',
      primaryDark: '#a87565',
      primaryLight: '#dbb5a5',
      secondary: '#6b8e7b',
      background: '#fdfaf8',
      surface: '#f5efeb',
      accent: '#d4a88c',
    },
    logoInitial: 'R',
    categories: ['Injectables', 'Laser Treatments', 'Skin Care', 'Body Contouring'],
    services: [
      { name: 'Botox', category: 'Injectables', price: 1200, duration: 30, description: 'Smooth fine lines and wrinkles with precision injections' },
      { name: 'Dermal Fillers', category: 'Injectables', price: 65000, duration: 45, description: 'Restore volume and enhance facial contours' },
      { name: 'Lip Filler', category: 'Injectables', price: 55000, duration: 30, description: 'Fuller, beautifully shaped lips', priceLabel: 'per syringe' },
      { name: 'Laser Hair Removal', category: 'Laser Treatments', price: 15000, duration: 30, description: 'Permanent hair reduction with advanced laser technology' },
      { name: 'IPL Photofacial', category: 'Laser Treatments', price: 35000, duration: 45, description: 'Reduce sun damage, redness, and pigmentation' },
      { name: 'Chemical Peel', category: 'Skin Care', price: 15000, duration: 30, description: 'Reveal fresh, glowing skin with professional-grade peels' },
      { name: 'Microneedling', category: 'Skin Care', price: 30000, duration: 60, description: 'Stimulate collagen production for smoother skin' },
      { name: 'HydraFacial', category: 'Skin Care', price: 19900, duration: 45, description: 'Deep cleanse, extract, and hydrate in one treatment' },
      { name: 'CoolSculpting', category: 'Body Contouring', price: 75000, duration: 60, description: 'Freeze away stubborn fat without surgery' },
      { name: 'Body Sculpting', category: 'Body Contouring', price: 50000, duration: 45, description: 'Non-invasive body toning and contouring' },
    ],
    staff: [
      { name: 'Dr. Sarah Mitchell', title: 'Medical Director', role: 'provider' },
      { name: 'Jessica Larson', title: 'Licensed Esthetician', role: 'provider' },
      { name: 'Amanda Reeves', title: 'Laser Specialist', role: 'provider' },
    ],
    promotions: [
      { title: 'New Client Special', body: '$50 off your first treatment of $200+', cta: 'Book Now' },
      { title: 'Spring Refresh Package', body: 'HydraFacial + Chemical Peel — Save $60', cta: 'View Details' },
    ],
    appFeatures: ['Online Booking', 'Wallet & Prepay', 'Loyalty Rewards', 'Push Notifications', 'Before/After Gallery', 'Treatment Packages'],
    pitchPoints: [
      'Replace phone-tag booking with 24/7 in-app scheduling',
      'Prepaid wallet increases average client spend by 30%',
      'Push notifications reduce no-shows by up to 40%',
      'Before/after gallery drives referrals',
    ],
  },

  // ─────────────────────────────────────────────
  // 2. MED SPA — Me Wellness (Loveland)
  // ─────────────────────────────────────────────
  {
    id: 'me-wellness',
    name: 'Me Wellness',
    tagline: 'Beauty From Within',
    type: 'Med Spa & Wellness',
    city: 'Loveland',
    state: 'CO',
    address: '320 E 4th St, Loveland, CO 80537',
    phone: '(970) 669-4234',
    website: 'mewellnessloveland.com',
    hours: {
      monday: { open: '09:00', close: '17:00' },
      tuesday: { open: '09:00', close: '17:00' },
      wednesday: { open: '09:00', close: '17:00' },
      thursday: { open: '09:00', close: '17:00' },
      friday: { open: '09:00', close: '15:00' },
      saturday: null,
      sunday: null,
    },
    colors: {
      primary: '#7ba7bc',
      primaryDark: '#5a8fa8',
      primaryLight: '#a3c4d4',
      secondary: '#d4a88c',
      background: '#f8fbfc',
      surface: '#edf4f7',
      accent: '#8bc5d4',
    },
    logoInitial: 'M',
    categories: ['IV Therapy', 'Injectables', 'Wellness', 'Skin Rejuvenation'],
    services: [
      { name: 'IV Vitamin Drip', category: 'IV Therapy', price: 17500, duration: 45, description: 'Boost energy and immunity with custom vitamin infusions' },
      { name: 'NAD+ Therapy', category: 'IV Therapy', price: 45000, duration: 90, description: 'Anti-aging cellular regeneration therapy' },
      { name: 'Botox', category: 'Injectables', price: 1200, duration: 30, description: 'Precision wrinkle reduction', priceLabel: 'per unit' },
      { name: 'Dermal Fillers', category: 'Injectables', price: 60000, duration: 45, description: 'Natural-looking volume restoration' },
      { name: 'B12 Injections', category: 'Wellness', price: 3500, duration: 15, description: 'Quick energy boost with vitamin B12' },
      { name: 'Hormone Therapy', category: 'Wellness', price: 35000, duration: 60, description: 'Bioidentical hormone optimization' },
      { name: 'PRP Facial', category: 'Skin Rejuvenation', price: 40000, duration: 60, description: 'Platelet-rich plasma for natural skin renewal' },
      { name: 'Microneedling', category: 'Skin Rejuvenation', price: 30000, duration: 60, description: 'Collagen induction therapy for skin texture' },
    ],
    staff: [
      { name: 'Dr. Megan Torres', title: 'Medical Director, DO', role: 'provider' },
      { name: 'Katie Owens, RN', title: 'Nurse Injector', role: 'provider' },
    ],
    promotions: [
      { title: 'First IV Drip Free', body: 'New clients get their first vitamin drip complimentary', cta: 'Claim Offer' },
      { title: 'Wellness Wednesday', body: '20% off all IV therapy every Wednesday', cta: 'Book Now' },
    ],
    appFeatures: ['Online Booking', 'Membership Plans', 'Treatment History', 'Push Notifications', 'Wellness Tracking', 'Referral Rewards'],
    pitchPoints: [
      'Minimal online presence — huge upside from branded mobile app',
      'Membership management built-in (recurring IV clients)',
      'Wellness tracking keeps clients engaged between visits',
      'Digital referral program grows client base organically',
    ],
  },

  // ─────────────────────────────────────────────
  // 3. NAIL SALON — Nail Bar Fort Collins
  // ─────────────────────────────────────────────
  {
    id: 'nail-bar-fc',
    name: 'Nail Bar Fort Collins',
    tagline: 'Nails Done Right',
    type: 'Nail Salon & Spa',
    city: 'Fort Collins',
    state: 'CO',
    address: '2842 Council Tree Ave #136, Fort Collins, CO 80525',
    phone: '(970) 672-8989',
    website: 'nailbarfc.com',
    hours: {
      monday: { open: '09:30', close: '19:00' },
      tuesday: { open: '09:30', close: '19:00' },
      wednesday: { open: '09:30', close: '19:00' },
      thursday: { open: '09:30', close: '19:00' },
      friday: { open: '09:30', close: '19:00' },
      saturday: { open: '09:00', close: '18:00' },
      sunday: { open: '11:00', close: '17:00' },
    },
    colors: {
      primary: '#e8a0bf',
      primaryDark: '#d4789e',
      primaryLight: '#f2c4da',
      secondary: '#c9a96e',
      background: '#fef9fb',
      surface: '#fdf0f5',
      accent: '#f5b8d0',
    },
    logoInitial: 'NB',
    categories: ['Manicures', 'Pedicures', 'Nail Art', 'Waxing'],
    services: [
      { name: 'Classic Manicure', category: 'Manicures', price: 2500, duration: 30, description: 'Shape, buff, cuticle care, and polish' },
      { name: 'Gel Manicure', category: 'Manicures', price: 4000, duration: 45, description: 'Long-lasting gel polish with chip-free shine' },
      { name: 'Dip Powder Manicure', category: 'Manicures', price: 4500, duration: 50, description: 'Durable dip powder for 3-4 week wear' },
      { name: 'Acrylic Full Set', category: 'Manicures', price: 5500, duration: 75, description: 'Full acrylic nail extensions with your choice of shape' },
      { name: 'Classic Pedicure', category: 'Pedicures', price: 3500, duration: 40, description: 'Soak, scrub, massage, and polish for happy feet' },
      { name: 'Luxury Spa Pedicure', category: 'Pedicures', price: 5500, duration: 60, description: 'Hot stone, paraffin wax, extended massage, and gel polish' },
      { name: 'Custom Nail Art', category: 'Nail Art', price: 1500, duration: 20, description: 'Hand-painted designs, rhinestones, and custom art', priceLabel: 'starting at' },
      { name: 'Eyebrow Wax', category: 'Waxing', price: 1500, duration: 15, description: 'Precision brow shaping' },
    ],
    staff: [
      { name: 'Kim Nguyen', title: 'Owner & Lead Nail Tech', role: 'provider' },
      { name: 'Lisa Tran', title: 'Senior Nail Artist', role: 'provider' },
      { name: 'Mia Pham', title: 'Nail Technician', role: 'provider' },
      { name: 'Sophie Chen', title: 'Nail Technician', role: 'provider' },
    ],
    promotions: [
      { title: 'Mani-Pedi Combo', body: 'Gel Mani + Spa Pedi for $75 (save $20)', cta: 'Book Now' },
      { title: 'Birthday Month Special', body: 'Free nail art upgrade during your birthday month', cta: 'Claim Offer' },
    ],
    appFeatures: ['Online Booking', 'Walk-in Queue', 'Loyalty Punch Card', 'Push Notifications', 'Nail Gallery', 'Gift Cards'],
    pitchPoints: [
      'Walk-in queue management eliminates lobby wait frustration',
      'Digital loyalty card replaces easily-lost paper cards',
      'Nail art gallery inspires clients and drives upsells',
      'Gift card integration drives holiday and birthday revenue',
    ],
  },

  // ─────────────────────────────────────────────
  // 4. NAIL SALON — Luxe Nails & Spa (Loveland)
  // ─────────────────────────────────────────────
  {
    id: 'luxe-nails',
    name: 'Luxe Nails & Spa',
    tagline: 'Luxury at Your Fingertips',
    type: 'Nail Salon',
    city: 'Loveland',
    state: 'CO',
    address: '1455 Rocky Mountain Ave, Loveland, CO 80538',
    phone: '(970) 685-4211',
    website: 'luxenailsloveland.com',
    hours: {
      monday: { open: '09:00', close: '19:00' },
      tuesday: { open: '09:00', close: '19:00' },
      wednesday: { open: '09:00', close: '19:00' },
      thursday: { open: '09:00', close: '19:00' },
      friday: { open: '09:00', close: '19:00' },
      saturday: { open: '09:00', close: '18:00' },
      sunday: { open: '10:00', close: '16:00' },
    },
    colors: {
      primary: '#b8860b',
      primaryDark: '#946d09',
      primaryLight: '#d4a632',
      secondary: '#2c2c2c',
      background: '#fffdf5',
      surface: '#f9f3e3',
      accent: '#c9a96e',
    },
    logoInitial: 'L',
    categories: ['Manicures', 'Pedicures', 'Enhancements', 'Add-Ons'],
    services: [
      { name: 'Signature Manicure', category: 'Manicures', price: 3000, duration: 35, description: 'Our signature manicure with hot towel and hand massage' },
      { name: 'Gel-X Extensions', category: 'Enhancements', price: 6500, duration: 60, description: 'Soft gel tip extensions — lightweight and natural' },
      { name: 'SNS Dip Powder', category: 'Manicures', price: 4500, duration: 50, description: 'Healthy dip powder nails with vitamin-infused formula' },
      { name: 'Deluxe Spa Pedicure', category: 'Pedicures', price: 5000, duration: 55, description: 'Sugar scrub, callus removal, collagen mask, and massage' },
      { name: 'Paraffin Treatment', category: 'Add-Ons', price: 1000, duration: 10, description: 'Warm paraffin wax for deep hand/foot moisturizing' },
      { name: 'Chrome/Ombre Nails', category: 'Enhancements', price: 2000, duration: 25, description: 'Trendy chrome mirror or ombre gradient finish', priceLabel: 'add-on' },
    ],
    staff: [
      { name: 'Tommy Le', title: 'Owner & Master Tech', role: 'provider' },
      { name: 'Jenny Vo', title: 'Senior Technician', role: 'provider' },
      { name: 'Anna Kim', title: 'Nail Technician', role: 'provider' },
    ],
    promotions: [
      { title: 'Grand Opening', body: '15% off all services this month', cta: 'Book Now' },
      { title: 'Refer a Friend', body: 'Both you and your friend get $10 off', cta: 'Share' },
    ],
    appFeatures: ['Online Booking', 'Loyalty Points', 'Walk-in Wait Times', 'Push Notifications', 'Style Inspiration', 'Prepaid Packages'],
    pitchPoints: [
      'Real-time walk-in wait time display reduces walkouts',
      'Prepaid packages lock in recurring revenue',
      'Style inspiration board drives appointment conversions',
      'Points-based loyalty program increases visit frequency',
    ],
  },

  // ─────────────────────────────────────────────
  // 5. HAIR SALON — Studio Be Salon & Spa (Fort Collins, 4 locations)
  // ─────────────────────────────────────────────
  {
    id: 'studio-be',
    name: 'Studio Be Salon & Spa',
    tagline: 'Be Bold. Be Beautiful. Be You.',
    type: 'Hair Salon & Spa',
    city: 'Fort Collins',
    state: 'CO',
    address: '1015 W Horsetooth Rd, Fort Collins, CO 80526',
    phone: '(970) 223-7487',
    website: 'studiobe.co',
    hours: {
      monday: { open: '09:00', close: '19:00' },
      tuesday: { open: '09:00', close: '19:00' },
      wednesday: { open: '09:00', close: '19:00' },
      thursday: { open: '09:00', close: '20:00' },
      friday: { open: '09:00', close: '19:00' },
      saturday: { open: '09:00', close: '17:00' },
      sunday: null,
    },
    colors: {
      primary: '#2d2d2d',
      primaryDark: '#1a1a1a',
      primaryLight: '#555555',
      secondary: '#c4917b',
      background: '#ffffff',
      surface: '#f7f5f3',
      accent: '#8b6f5e',
    },
    logoInitial: 'SB',
    categories: ['Hair Cuts', 'Color & Highlights', 'Treatments', 'Spa Services', 'Blowouts'],
    services: [
      { name: "Women's Haircut", category: 'Hair Cuts', price: 5500, duration: 60, description: 'Consultation, shampoo, precision cut, and style' },
      { name: "Men's Haircut", category: 'Hair Cuts', price: 3500, duration: 30, description: 'Classic or modern cut with hot towel finish' },
      { name: 'Balayage', category: 'Color & Highlights', price: 18000, duration: 150, description: 'Hand-painted highlights for a natural, sun-kissed look' },
      { name: 'Full Highlights', category: 'Color & Highlights', price: 15000, duration: 120, description: 'Full foil highlights with toner and gloss' },
      { name: 'Root Touch-Up', category: 'Color & Highlights', price: 7500, duration: 60, description: 'Color refresh at the roots with seamless blending' },
      { name: 'Keratin Treatment', category: 'Treatments', price: 25000, duration: 120, description: 'Smooth frizz and add lasting shine for 3-5 months' },
      { name: 'Deep Conditioning', category: 'Treatments', price: 3500, duration: 20, description: 'Intensive moisture and repair treatment' },
      { name: 'Blowout & Style', category: 'Blowouts', price: 4500, duration: 45, description: 'Professional blowout with styling' },
      { name: 'Facial', category: 'Spa Services', price: 9500, duration: 60, description: 'Customized facial treatment for glowing skin' },
      { name: 'Eyebrow Wax & Tint', category: 'Spa Services', price: 3500, duration: 25, description: 'Shape and define your brows' },
    ],
    staff: [
      { name: 'Brittany Edwards', title: 'Owner & Master Stylist', role: 'provider' },
      { name: 'Rachel Kim', title: 'Senior Colorist', role: 'provider' },
      { name: 'Taylor James', title: 'Stylist', role: 'provider' },
      { name: 'Megan Hart', title: 'Esthetician', role: 'provider' },
      { name: 'Chris DeLuca', title: 'Barber', role: 'provider' },
    ],
    promotions: [
      { title: 'New Guest Offer', body: '20% off your first color service', cta: 'Book Now' },
      { title: 'Blowout Membership', body: 'Unlimited blowouts for $99/month', cta: 'Join' },
    ],
    appFeatures: ['Online Booking', 'Multi-Location Support', 'Stylist Portfolios', 'Push Notifications', 'Product Shop', 'Membership Plans'],
    pitchPoints: [
      '4 locations managed from one app with location picker',
      'Stylist portfolios help clients choose their perfect match',
      'Blowout membership drives predictable recurring revenue',
      'In-app product shop extends revenue beyond the chair',
    ],
  },

  // ─────────────────────────────────────────────
  // 6. BARBERSHOP — The Parlour Barber Shop (Fort Collins)
  // ─────────────────────────────────────────────
  {
    id: 'parlour-barber',
    name: 'The Parlour Barber Shop',
    tagline: 'Classic Cuts. Modern Edge.',
    type: 'Barbershop',
    city: 'Fort Collins',
    state: 'CO',
    address: '232 Walnut St, Fort Collins, CO 80524',
    phone: '(970) 224-5780',
    website: 'parlourbarbers.com',
    hours: {
      monday: null,
      tuesday: { open: '09:00', close: '18:00' },
      wednesday: { open: '09:00', close: '18:00' },
      thursday: { open: '09:00', close: '18:00' },
      friday: { open: '09:00', close: '18:00' },
      saturday: { open: '08:00', close: '16:00' },
      sunday: null,
    },
    colors: {
      primary: '#1a3a4a',
      primaryDark: '#0f2a36',
      primaryLight: '#2d5a6e',
      secondary: '#c17f3e',
      background: '#faf8f5',
      surface: '#f0ece6',
      accent: '#d4a16a',
    },
    logoInitial: 'P',
    categories: ['Haircuts', 'Beard Services', 'Premium Services', 'Grooming'],
    services: [
      { name: 'Classic Haircut', category: 'Haircuts', price: 3500, duration: 30, description: 'Precision cut with hot towel and style' },
      { name: 'Skin Fade', category: 'Haircuts', price: 4000, duration: 40, description: 'Sharp skin fade with lineup and detail work' },
      { name: "Kid's Cut", category: 'Haircuts', price: 2500, duration: 25, description: 'Haircut for kids 12 and under' },
      { name: 'Beard Trim', category: 'Beard Services', price: 2000, duration: 20, description: 'Shape, line up, and condition your beard' },
      { name: 'Hot Towel Shave', category: 'Beard Services', price: 3500, duration: 30, description: 'Classic straight-razor shave with hot towels' },
      { name: 'Cut & Beard Combo', category: 'Premium Services', price: 5000, duration: 50, description: 'Full haircut plus beard trim and shaping' },
      { name: 'The Works', category: 'Premium Services', price: 6500, duration: 60, description: 'Haircut, hot towel shave, scalp massage, and style' },
      { name: 'Hair & Scalp Treatment', category: 'Grooming', price: 2500, duration: 20, description: 'Deep conditioning treatment for healthy hair' },
    ],
    staff: [
      { name: 'Jake Morrison', title: 'Owner & Master Barber', role: 'provider' },
      { name: 'Devin Carter', title: 'Senior Barber', role: 'provider' },
      { name: 'Marcus Johnson', title: 'Barber', role: 'provider' },
    ],
    promotions: [
      { title: 'First Cut Free', body: 'New clients get their first classic cut on us', cta: 'Book Now' },
      { title: 'Father & Son Special', body: 'Dad + kid haircuts for $45 (save $15)', cta: 'Book' },
    ],
    appFeatures: ['Online Booking', 'Barber Selection', 'Walk-in Queue', 'Push Notifications', 'Loyalty Stamps', 'Product Orders'],
    pitchPoints: [
      'Walk-in queue with live wait times — clients join from their phone',
      'Barber selection lets regulars book their preferred barber',
      'Digital loyalty stamps: 10th haircut free drives retention',
      'Old Town Fort Collins foot traffic = huge walk-in potential',
    ],
  },

  // ─────────────────────────────────────────────
  // 7. FITNESS STUDIO — Muv Fitness Fort Collins
  // ─────────────────────────────────────────────
  {
    id: 'muv-fitness',
    name: 'Muv Fitness',
    tagline: 'Move Better. Live Better.',
    type: 'Fitness Studio',
    city: 'Fort Collins',
    state: 'CO',
    address: '225 N Lemay Ave, Fort Collins, CO 80524',
    phone: '(970) 482-0444',
    website: 'muvfitness.com',
    hours: {
      monday: { open: '05:00', close: '21:00' },
      tuesday: { open: '05:00', close: '21:00' },
      wednesday: { open: '05:00', close: '21:00' },
      thursday: { open: '05:00', close: '21:00' },
      friday: { open: '05:00', close: '20:00' },
      saturday: { open: '07:00', close: '17:00' },
      sunday: { open: '08:00', close: '15:00' },
    },
    colors: {
      primary: '#ff5722',
      primaryDark: '#e64a19',
      primaryLight: '#ff8a65',
      secondary: '#212121',
      background: '#ffffff',
      surface: '#fafafa',
      accent: '#ff7043',
    },
    logoInitial: 'M',
    categories: ['Group Classes', 'Personal Training', 'Memberships', 'Recovery'],
    services: [
      { name: 'HIIT Blast', category: 'Group Classes', price: 2000, duration: 45, description: 'High-intensity interval training to torch calories' },
      { name: 'Yoga Flow', category: 'Group Classes', price: 1800, duration: 60, description: 'Vinyasa-style flow for strength and flexibility' },
      { name: 'Spin Class', category: 'Group Classes', price: 2000, duration: 45, description: 'High-energy indoor cycling with motivating music' },
      { name: 'Strength & Conditioning', category: 'Group Classes', price: 2000, duration: 50, description: 'Full-body strength training with progressive overload' },
      { name: '1-on-1 Training Session', category: 'Personal Training', price: 7500, duration: 60, description: 'Personalized workout with a certified trainer' },
      { name: '5-Pack Training', category: 'Personal Training', price: 32500, duration: 60, description: 'Five personal training sessions at a discounted rate', priceLabel: '5 sessions' },
      { name: 'Monthly Unlimited', category: 'Memberships', price: 7900, duration: 0, description: 'Unlimited classes and gym access', priceLabel: 'per month' },
      { name: 'Infrared Sauna', category: 'Recovery', price: 2500, duration: 30, description: 'Deep heat therapy for muscle recovery and relaxation' },
    ],
    staff: [
      { name: 'Coach Ryan', title: 'Head Trainer & Owner', role: 'provider' },
      { name: 'Coach Alicia', title: 'Yoga & Mobility Specialist', role: 'provider' },
      { name: 'Coach Derek', title: 'Strength Coach', role: 'provider' },
      { name: 'Coach Samantha', title: 'Spin Instructor', role: 'provider' },
    ],
    promotions: [
      { title: '7-Day Free Trial', body: 'Try unlimited classes for a full week — no commitment', cta: 'Start Trial' },
      { title: 'Bring a Friend Month', body: 'Members bring one guest free all February', cta: 'Learn More' },
    ],
    appFeatures: ['Class Scheduling', 'Membership Management', 'Workout Tracking', 'Push Notifications', 'Trainer Booking', 'Progress Photos'],
    pitchPoints: [
      'Class booking with live availability prevents overcrowding',
      'Workout tracking keeps members engaged and reduces churn',
      'Membership management with auto-billing built in',
      'Progress photos and milestones drive social sharing',
    ],
  },

  // ─────────────────────────────────────────────
  // 8. YOGA / PILATES — Inner Strength Pilates (Windsor)
  // ─────────────────────────────────────────────
  {
    id: 'inner-strength',
    name: 'Inner Strength Pilates',
    tagline: 'Strength From the Inside Out',
    type: 'Pilates Studio',
    city: 'Windsor',
    state: 'CO',
    address: '1265 Main St, Windsor, CO 80550',
    phone: '(970) 460-2235',
    website: 'innerstrengthpilates.com',
    hours: {
      monday: { open: '06:00', close: '19:00' },
      tuesday: { open: '06:00', close: '19:00' },
      wednesday: { open: '06:00', close: '19:00' },
      thursday: { open: '06:00', close: '19:00' },
      friday: { open: '06:00', close: '17:00' },
      saturday: { open: '08:00', close: '12:00' },
      sunday: null,
    },
    colors: {
      primary: '#5b7a5e',
      primaryDark: '#456348',
      primaryLight: '#7fa882',
      secondary: '#d4c5a0',
      background: '#f9faf7',
      surface: '#f0f3ed',
      accent: '#8db88f',
    },
    logoInitial: 'IS',
    categories: ['Mat Classes', 'Reformer Classes', 'Private Sessions', 'Workshops'],
    services: [
      { name: 'Mat Pilates', category: 'Mat Classes', price: 2200, duration: 55, description: 'Core-focused mat work for all levels' },
      { name: 'Reformer Pilates', category: 'Reformer Classes', price: 3500, duration: 55, description: 'Full-body reformer workout with spring resistance' },
      { name: 'Barre Fusion', category: 'Mat Classes', price: 2200, duration: 50, description: 'Ballet-inspired sculpting with pilates principles' },
      { name: 'Private Reformer', category: 'Private Sessions', price: 8500, duration: 55, description: 'One-on-one reformer session tailored to your goals' },
      { name: 'Duet Session', category: 'Private Sessions', price: 12000, duration: 55, description: 'Semi-private session for two', priceLabel: 'per pair' },
      { name: 'Prenatal Pilates', category: 'Mat Classes', price: 2200, duration: 45, description: 'Gentle strengthening designed for expecting mothers' },
      { name: 'Intro Workshop', category: 'Workshops', price: 4500, duration: 90, description: 'Learn the fundamentals in a small group setting' },
    ],
    staff: [
      { name: 'Jennifer Lane', title: 'Owner & BASI-Certified Instructor', role: 'provider' },
      { name: 'Rebecca Stone', title: 'Reformer Specialist', role: 'provider' },
      { name: 'Amy Collins', title: 'Prenatal & Recovery Instructor', role: 'provider' },
    ],
    promotions: [
      { title: 'Intro Package', body: '3 classes for $49 (new clients only)', cta: 'Get Started' },
      { title: 'Monthly Unlimited', body: 'Unlimited mat + reformer classes for $149/mo', cta: 'Subscribe' },
    ],
    appFeatures: ['Class Scheduling', 'Class Packs', 'Waitlist Management', 'Push Notifications', 'Instructor Selection', 'Auto-Renew Memberships'],
    pitchPoints: [
      'Reformer classes have limited spots — waitlist drives urgency',
      'Class pack purchases ensure upfront revenue commitment',
      'Auto-renewing memberships reduce administrative overhead',
      'Push notifications fill last-minute cancellation spots',
    ],
  },

  // ─────────────────────────────────────────────
  // 9. PET GROOMING — The Dog Pawlour (Greeley/Evans)
  // ─────────────────────────────────────────────
  {
    id: 'dog-pawlour',
    name: 'The Dog Pawlour',
    tagline: 'Where Every Pup is a VIP',
    type: 'Pet Grooming',
    city: 'Greeley',
    state: 'CO',
    address: '3500 23rd Ave, Greeley, CO 80631',
    phone: '(970) 330-7297',
    website: 'thedogpawlour.com',
    hours: {
      monday: { open: '07:30', close: '17:00' },
      tuesday: { open: '07:30', close: '17:00' },
      wednesday: { open: '07:30', close: '17:00' },
      thursday: { open: '07:30', close: '17:00' },
      friday: { open: '07:30', close: '17:00' },
      saturday: { open: '08:00', close: '14:00' },
      sunday: null,
    },
    colors: {
      primary: '#4a90d9',
      primaryDark: '#3672b5',
      primaryLight: '#7ab3ea',
      secondary: '#f5a623',
      background: '#f8fbff',
      surface: '#eef5fc',
      accent: '#5ba3e8',
    },
    logoInitial: 'DP',
    categories: ['Full Groom', 'Bath & Brush', 'Add-Ons', 'Specialty'],
    services: [
      { name: 'Full Groom - Small', category: 'Full Groom', price: 5500, duration: 90, description: 'Bath, dry, haircut, nails, ears, and anal glands (up to 25 lbs)' },
      { name: 'Full Groom - Medium', category: 'Full Groom', price: 7000, duration: 105, description: 'Complete grooming for medium breeds (25-50 lbs)' },
      { name: 'Full Groom - Large', category: 'Full Groom', price: 8500, duration: 120, description: 'Full service for large breeds (50-80 lbs)' },
      { name: 'Full Groom - XL', category: 'Full Groom', price: 10000, duration: 150, description: 'Full service for extra large breeds (80+ lbs)' },
      { name: 'Bath & Brush - Small', category: 'Bath & Brush', price: 3500, duration: 60, description: 'Bath, blow dry, brush out, nails, ears' },
      { name: 'Bath & Brush - Large', category: 'Bath & Brush', price: 5500, duration: 90, description: 'Full bath service for large breeds' },
      { name: 'Nail Trim Only', category: 'Add-Ons', price: 1500, duration: 15, description: 'Quick nail clip and file' },
      { name: 'De-Shedding Treatment', category: 'Specialty', price: 2500, duration: 30, description: 'Specialized treatment to reduce shedding up to 80%', priceLabel: 'add-on' },
      { name: 'Flea & Tick Treatment', category: 'Specialty', price: 2000, duration: 15, description: 'Medicated bath for flea and tick prevention', priceLabel: 'add-on' },
    ],
    staff: [
      { name: 'Heather Mills', title: 'Owner & Lead Groomer', role: 'provider' },
      { name: 'Courtney Blake', title: 'Certified Groomer', role: 'provider' },
      { name: 'Tyler Ross', title: 'Bath Technician', role: 'provider' },
    ],
    promotions: [
      { title: 'Puppy First Groom', body: "Puppy's first groom 20% off — positive introduction", cta: 'Book Now' },
      { title: '6-Week Plan', body: 'Pre-book 6 grooms, get the 7th free', cta: 'Subscribe' },
    ],
    appFeatures: ['Online Booking', 'Pet Profiles', 'Grooming History', 'Push Notifications', 'Photo Updates', 'Vaccination Tracking'],
    pitchPoints: [
      'Pet profiles store breed, weight, temperament, and preferences',
      'Photo updates sent during grooming reduce owner anxiety',
      'Vaccination tracking ensures compliance and builds trust',
      'Recurring 6-week booking cycles lock in predictable revenue',
    ],
  },

  // ─────────────────────────────────────────────
  // 10. CHIROPRACTIC — Advanced Health Chiropractic (Greeley)
  // ─────────────────────────────────────────────
  {
    id: 'advanced-health',
    name: 'Advanced Health Chiropractic',
    tagline: 'Align. Heal. Thrive.',
    type: 'Chiropractic & Wellness',
    city: 'Greeley',
    state: 'CO',
    address: '3801 W 10th St, Greeley, CO 80634',
    phone: '(970) 356-5255',
    website: 'advancedhealthgreeley.com',
    hours: {
      monday: { open: '08:00', close: '17:30' },
      tuesday: { open: '08:00', close: '17:30' },
      wednesday: { open: '08:00', close: '17:30' },
      thursday: { open: '08:00', close: '17:30' },
      friday: { open: '08:00', close: '15:00' },
      saturday: null,
      sunday: null,
    },
    colors: {
      primary: '#2e7d5b',
      primaryDark: '#1e5e43',
      primaryLight: '#4a9e78',
      secondary: '#3d5a80',
      background: '#f7faf8',
      surface: '#ebf3ee',
      accent: '#5eb88a',
    },
    logoInitial: 'AH',
    categories: ['Adjustments', 'Therapy', 'Rehabilitation', 'Wellness'],
    services: [
      { name: 'Chiropractic Adjustment', category: 'Adjustments', price: 6500, duration: 30, description: 'Spinal adjustment to restore proper alignment and mobility' },
      { name: 'New Patient Exam', category: 'Adjustments', price: 15000, duration: 60, description: 'Comprehensive exam with X-rays, posture analysis, and treatment plan' },
      { name: 'Spinal Decompression', category: 'Therapy', price: 8500, duration: 30, description: 'Non-surgical decompression for disc-related pain' },
      { name: 'Massage Therapy', category: 'Therapy', price: 8000, duration: 60, description: 'Therapeutic massage focused on pain relief and recovery' },
      { name: 'Electrical Stimulation', category: 'Therapy', price: 3500, duration: 20, description: 'E-stim therapy for muscle pain and inflammation' },
      { name: 'Corrective Exercise', category: 'Rehabilitation', price: 5000, duration: 30, description: 'Guided exercise program for posture and strength' },
      { name: 'Nutritional Consultation', category: 'Wellness', price: 7500, duration: 45, description: 'Personalized nutrition guidance for optimal health' },
      { name: 'Wellness Check-Up', category: 'Wellness', price: 4500, duration: 20, description: 'Quick alignment check and maintenance adjustment' },
    ],
    staff: [
      { name: 'Dr. James Peterson, DC', title: 'Lead Chiropractor', role: 'provider' },
      { name: 'Dr. Lisa Chang, DC', title: 'Associate Chiropractor', role: 'provider' },
      { name: 'Mike Torres, LMT', title: 'Licensed Massage Therapist', role: 'provider' },
    ],
    promotions: [
      { title: 'New Patient Special', body: 'Complete exam + X-rays + first adjustment for $79 (save $120)', cta: 'Schedule Now' },
      { title: 'Family Plan', body: 'Family of 4+ gets 15% off all services', cta: 'Learn More' },
    ],
    appFeatures: ['Online Booking', 'Treatment Plans', 'Progress Tracking', 'Push Notifications', 'Insurance Info', 'Exercise Library'],
    pitchPoints: [
      'Treatment plan tracking keeps patients accountable to their care',
      'Exercise library with video guides reduces in-office time',
      'Insurance info storage streamlines check-in process',
      'Appointment reminders reduce costly no-shows (avg $65/missed)',
    ],
  },
];
